common:
  main_mode: 1
  failed_output_folder: failed
  success_output_folder: output
  failed_move: 1
  auto_exit: 1
  transalte_to_sc: 1
proxy:
  enable: False
  type: socks5
  host:
request:
  timeout: 5
  total: 3
  delay: 1
  enable_free_proxy_pool: False
  free_proxy_pool: [ ]
  javbd_cookie: ''
priority:
  website: [ "javbus", "javdb" ]
name_rule:
  location_rule: actor/number
  naming_rule: number-title
  max_title_len: 50
exclude:
  folders: [ failed, output, escape ]
debug:
  enable: True
  check_number_parser: True
