common:
  debug: True
  main_mode: 1
  failed_output_folder: failed
  success_output_folder: output
  failed_move: 1
  auto_exit: 1
  transalte_to_sc: 1
proxy:
  enable: False
  type: socks5
  host: 
name_rule:
  location_rule: actor/number
  naming_rule: number-title
  max_title_len: 50
exclude:
  folders: [failed,output,escape]